name: AndroidTest

on:
  push:
    branches: dev

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: unittest-android
        uses: msfjarvis/setup-android@0.2
        with:
          entrypoint: ./App/gradlew
          args: test
      - name: connectedtest-android
        uses: msfjarvis/setup-android@0.2
        with:
          entrypoint: ./App/gradlew
          args: connectAndroidTest
